# Semana 1: carga, transformaci?n y reporte del dataset Iris

Este notebook carga el dataset `scikit-learn/iris` desde Hugging Face, transforma sus datos y genera un resumen `.txt` del DataFrame final.

Flujo de trabajo:
1. Importar las clases reutilizables del proyecto.
2. Cargar el dataset como un DataFrame de pandas.
3. Aplicar cuatro transformaciones y observar cada resultado.
4. Generar y guardar el resumen de los datos transformados.

Ejecuta las celdas en orden. El dataset es p?blico y normalmente no requiere autenticaci?n.

## 1. Preparar el entorno e importar las clases

El notebook busca la ra?z del proyecto para importar `HFDatasetLoader` y `Reportes`. Tambi?n define rutas estables para guardar los archivos aunque el notebook se ejecute desde otra carpeta.

In [1]:
import sys
from pathlib import Path

ROOT = Path.cwd().resolve()
while ROOT != ROOT.parent and not (ROOT / "src" / "clases_po").exists():
    ROOT = ROOT.parent

if not (ROOT / "src" / "clases_po").exists():
    raise FileNotFoundError("No se encontr? src/clases_po desde el directorio actual.")

sys.path.insert(0, str(ROOT / "src"))

from clases_po import HFDatasetLoader, Reportes

DATA_DIR = ROOT / "src" / "sincronicas" / "datos"
REPORT_DIR = ROOT / "src" / "sincronicas" / "reportes"

/home/runner/work/proyecto-integrador-3/proyecto-integrador-3/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## 2. Configurar y cargar el dataset

`scikit-learn/iris` contiene mediciones de s?palos y p?talos para tres especies de iris. `HFDatasetLoader` obtiene la divisi?n `train`, la convierte a DataFrame y guarda una copia CSV de los datos originales.

In [2]:
loader = HFDatasetLoader(
    dataset_name="scikit-learn/iris",
    split="train",
    filename=DATA_DIR / "iris.csv",
)

df = loader.load()
print(f"Dataset cargado: {len(df)} filas y {len(df.columns)} columnas")
df.head()

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Generating train split:   0%|          | 0/150 [00:00<?, ? examples/s]

Generating train split: 100%|██████████| 150/150 [00:00<00:00, 37176.95 examples/s]

Dataset cargado: 150 filas y 6 columnas

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

## 3. Revisar la estructura original

Antes de transformar, revisamos las columnas, sus tipos y los valores no nulos del DataFrame descargado.

In [3]:
print(f"Filas: {len(df)}")
print(f"Columnas: {len(df.columns)}")
df.info()

Filas: 150
Columnas: 6
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

## 4. Transformaci?n 1: retirar el identificador

La columna `Id` solo identifica cada fila y no es una medici?n de la flor, por eso se elimina.

In [4]:
df_transformado = df.drop(columns=["Id"])
df_transformado.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

## 5. Transformaci?n 2: renombrar columnas

Renombramos las variables al espa?ol para que el DataFrame sea m?s f?cil de interpretar.

In [5]:
df_transformado = df_transformado.rename(columns={
    "SepalLengthCm": "longitud_sepalo_cm",
    "SepalWidthCm": "ancho_sepalo_cm",
    "PetalLengthCm": "longitud_petalo_cm",
    "PetalWidthCm": "ancho_petalo_cm",
    "Species": "especie",
})
df_transformado.head()

,longitud_sepalo_cm,ancho_sepalo_cm,longitud_petalo_cm,ancho_petalo_cm,especie
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa

## 6. Transformaci?n 3: filtrar una especie

Seleccionamos las flores `Iris-setosa` para observar un subconjunto espec?fico. El resultado contiene 50 filas.

In [6]:
df_transformado = df_transformado.loc[
    df_transformado["especie"] == "Iris-setosa"
].copy()
print(f"Filas despu?s del filtro: {len(df_transformado)}")
df_transformado.head()

Filas despu?s del filtro: 50

,longitud_sepalo_cm,ancho_sepalo_cm,longitud_petalo_cm,ancho_petalo_cm,especie
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa

## 7. Transformaci?n 4: crear una variable derivada

Calculamos un ?rea aproximada del p?talo multiplicando su longitud por su ancho, ambas medidas en cent?metros.

In [7]:
df_transformado["area_petalo_aprox_cm2"] = (
    df_transformado["longitud_petalo_cm"] * df_transformado["ancho_petalo_cm"]
)
df_transformado.head()

,longitud_sepalo_cm,ancho_sepalo_cm,longitud_petalo_cm,ancho_petalo_cm,especie,area_petalo_aprox_cm2
0,5.1,3.5,1.4,0.2,Iris-setosa,0.28
1,4.9,3.0,1.4,0.2,Iris-setosa,0.28
2,4.7,3.2,1.3,0.2,Iris-setosa,0.26
3,4.6,3.1,1.5,0.2,Iris-setosa,0.30
4,5.0,3.6,1.4,0.2,Iris-setosa,0.28

## 8. Generar el resumen del DataFrame transformado

La clase `Reportes` recibe el DataFrame final, muestra sus dimensiones, tipos de columnas, valores nulos y estad?sticas num?ricas.

In [8]:
reportes = Reportes()
texto = reportes.generar_reporte(df_transformado)
print(texto)

REPORTE DEL DATAFRAME
============================================================
Filas: 50
Columnas: 6
Duplicados: 2

Columnas y tipos:
- longitud_sepalo_cm: float64
- ancho_sepalo_cm: float64
- longitud_petalo_cm: float64
- ancho_petalo_cm: float64
- especie: object
- area_petalo_aprox_cm2: float64

Valores nulos por columna:
- longitud_sepalo_cm: 0
- ancho_sepalo_cm: 0
- longitud_petalo_cm: 0
- ancho_petalo_cm: 0
- especie: 0
- area_petalo_aprox_cm2: 0

Estadísticas numéricas:
       longitud_sepalo_cm  ancho_sepalo_cm  longitud_petalo_cm  ancho_petalo_cm  area_petalo_aprox_cm2
count              50.000           50.000              50.000           50.000                 50.000
mean                5.006            3.418               1.464            0.244                  0.363
std                 0.352            0.381               0.174            0.107                  0.183
min                 4.300            2.300               1.000            0.100                  0.110
25%                 4.800            3.125               1.400            0.200                  0.265
50%                 5.000            3.400               1.500            0.200                  0.300
75%                 5.200            3.675               1.575            0.300                  0.420
max                 5.800            4.400               1.900            0.600                  0.960

## 9. Guardar el resumen en un archivo `.txt`

El reporte corresponde al DataFrame transformado (filtrado a `Iris-setosa` y con la variable derivada) y queda guardado en `src/sincronicas/reportes/iris.txt`.

In [9]:
ruta = reportes.guardar_reporte(
    df_transformado,
    REPORT_DIR / "iris.txt",
)
print(f"Reporte guardado en: {ruta}")

Reporte guardado en: /home/runner/work/proyecto-integrador-3/proyecto-integrador-3/src/sincronicas/reportes/iris.txt